# Generated by Django 4.2.3 on 2023-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaixasHf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInicial', models.CharField(max_length=20)),
                ('HoraInicial', models.CharField(max_length=20)),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalVendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CartaoCredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CartaoDebito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cheque', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Sangria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SomaTotalCaixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalCaixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VendasPrazo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Despesas', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('DataFinal', models.CharField(max_length=20)),
                ('HoraFinal', models.CharField(max_length=20)),
                ('Operador', models.CharField(max_length=20)),
                ('VendasRecebidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EntradaDeNotas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CaixasSm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataInicial', models.CharField(max_length=20)),
                ('HoraInicial', models.CharField(max_length=20)),
                ('SaldoInicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalVendas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Pix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CartaoCredito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('CartaoDebito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cheque', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Sangria', models.DecimalField(decimal_places=2, max_digits=10)),
                ('SomaTotalCaixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TotalCaixa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DataFinal', models.CharField(max_length=20)),
                ('HoraFinal', models.CharField(max_length=20)),
                ('Operador', models.CharField(max_length=20)),
                ('VendasRecebidas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Desconto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('EntradaDeNotas', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_de_notas_Hf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fornecedor', models.CharField(max_length=100)),
                ('TotalPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TipoDeEntrada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Entrada_de_notas_Sm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fornecedor', models.CharField(max_length=100)),
                ('TotalPagar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('TipoDeEntrada', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sangria_Hf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cheque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descriacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sangria_Sm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dinheiro', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Cheque', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Descriacao', models.CharField(max_length=100)),
            ],
        ),
    ]
