# Generated by Django 4.2.3 on 2023-08-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixashf',
            name='CodigoCaixa',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixassm',
            name='CodigoCaixa',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixassm',
            name='VendasAPrazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
