# Generated by Django 4.2.3 on 2023-08-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0002_caixashf_codigocaixa_caixassm_codigocaixa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_de_notas_hf',
            name='DataEmissão',
            field=models.CharField(default='1/1/23', max_length=20),
        ),
        migrations.AddField(
            model_name='entrada_de_notas_sm',
            name='DataEmissão',
            field=models.CharField(default='1/1/23', max_length=20),
        ),
        migrations.AddField(
            model_name='sangria_hf',
            name='Data',
            field=models.CharField(default='1/1/23', max_length=20),
        ),
        migrations.AddField(
            model_name='sangria_sm',
            name='Data',
            field=models.CharField(default='1/1/23', max_length=20),
        ),
    ]
