# Generated by Django 4.2.3 on 2023-08-03 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0004_sangria_hf_codigo_caixa_sangria_sm_codigo_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixashf',
            name='CartaoCredito',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='CartaoDebito',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Cheque',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Desconto',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Despesas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Dinheiro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='EntradaDeNotas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Pix',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='SaldoInicial',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='Sangria',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='SomaTotalCaixa',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='TotalCaixa',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='TotalVendas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='VendasPrazo',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixashf',
            name='VendasRecebidas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='CartaoCredito',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='CartaoDebito',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='Cheque',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='Desconto',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='Dinheiro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='EntradaDeNotas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='Pix',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='SaldoInicial',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='Sangria',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='SomaTotalCaixa',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='TotalCaixa',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='TotalVendas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='VendasAPrazo',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='caixassm',
            name='VendasRecebidas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada_de_notas_hf',
            name='TotalPagar',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='entrada_de_notas_sm',
            name='TotalPagar',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_hf',
            name='Cheque',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_hf',
            name='Dinheiro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_hf',
            name='Total',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_sm',
            name='Cheque',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_sm',
            name='Dinheiro',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='sangria_sm',
            name='Total',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
