# Generated by Django 4.2.3 on 2023-08-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixas', '0005_alter_caixashf_cartaocredito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada_de_notas_hf',
            name='Codigo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='entrada_de_notas_sm',
            name='Codigo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='sangria_hf',
            name='Codigo',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='sangria_sm',
            name='Codigo',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
