# Generated by Django 4.2.3 on 2023-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Precos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo', models.IntegerField()),
                ('Produto', models.CharField(max_length=255)),
                ('VlrCompra', models.CharField(max_length=255)),
                ('VlrVenda', models.CharField(max_length=255)),
            ],
        ),
    ]
